### ISSUE TITLE
Recheck for duplicate payloads

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#117]
[link to conversation](https://chat.zulip.org/#narrow/stream/zulipbot/topic/duplicated.20notices)

**Comment by synicalsyntax** [comment]
There isn't an issue with duplicate payloads. The issue lies with the fact that payloads were delayed and once they were sent they no longer reflected the real-time data.

Additionally, considering zulipbot operates on one payload at a time doesn't keep track of what payloads it has received, it's not very much in the interest of the project as we'd have to implement some form of persistent data storage. Looking to close this.

**Comment by lonerz** [comment]
Makes sense. Persistent data storage may be a really nice long term project.
