### ISSUE TITLE
Inactivity check doesn't account for closed issue references

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#128]
If an issue is closed, it is automatically disregarded as a reference. So, if someone claims an issue 8 days ago, opens a PR that references the issue 6 days ago and that PR gets merged and closed, zulipbot still comments on the original issue as it being inactive.

See https://github.com/zulip/zulip/pull/6542

**Comment by synicalsyntax** [comment]
I'm not sure what the context for the issue is, but why is the closed PR being updated when a new followup PR can be created instead?

Regardless, checking for closed PRs would be very, very expensive request-wise (currently 4268 closed PRs in zulip/zulip repo) and I don't think they should be checked for references.
