### ISSUE TITLE
Claim task should get rid of "help wanted" label

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#15]
When someone claims a task, the "help wanted" label should be removed (first check if it even exists). However, when someone abandons an issue, we should consider adding the "help wanted" label... Need feedback on this.

**Comment by lonerz** [comment]
@zulipbot label "help wanted"

**Comment by synicalsyntax** [comment]
Tagging @timabbott for feedback.

**Comment by timabbott** [comment]
Hmm, good question.  I'm sorta unsure whether the "help wanted" label is super useful, in that probably just about everything that isn't assigned should have the label; so we could either do this tagging approach, or perhaps get rid of it and just document that help is wanted on just about everything.

I guess I've been adding it mostly because it feels more friendly to have lots of things advertising help wanted (and I do leave it off for issues that don't have a concrete next step; those usually have "feedback wanted"), so there is some value in having it.

@brainwane what are your thoughts?

**Comment by brainwane** [comment]
I do think that claiming an issue should cause the bot to remove "help wanted".

I think the "help wanted" tag is useful in cases where there is a well-laid-out concrete next step -- but if someone abandons an issue then there's a fair chance that there is NOT a nicely concrete next step. So I think that the "help wanted" tag shouldn't necessarily automatically return to a newly abandoned task.
