### ISSUE TITLE
Make zulipbot customizable for community use

### ISSUE THREAD

**Issue by synicalsyntax** [zulip/zulipbot#68]
Currently a lot of settings for zulipbot are hardcoded, ranging from comment escaping to the inactivity times to the area labels.

Since @brainwane is presenting about zulipbot in about a week, I think it'd be great if we could make zulipbot more customizable in case others want to use their own copy of zulipbot to collaborate on their repositories. To make this possible, we would need to refactor the code to make configuration options for enabling/disabling all zulipbot features and some other settings like area labels/inactivity times.

**Currently supported options (updated 3/17)**
* Username
* Password
* Area labels & teams
* Inactive issue/PR time limit
* Abandon issue time limit
* Travis webhook notifications (for finished build statuses)
* Travis updates label name
* Self-labeling (only issue/PR authors can manage their issue/PR labels with `@zulipbot label` & `@zulipbot remove`
* Inactivity check timeout (how often zulipbot checks for inactive issues/PRs)
* Enable/disable adding in progress label to claimed issues
* Custom in progress label name
* Enable/disable inactive issue/PR tracking
* Repository access when collaborator is added (pull, push, write, etc.)
* Comment templates
* Enable/disable PR "review"/"needs review" system
* Label names of PR "review"/"needs review" system

**Comment by timabbott** [comment]
I think this is a great plan.  Since we have a configuration file setup already, it seems like we could push the content into that.  Though it might be a good idea to separate configuration into two things -- the public configuration vs. the secret keys.  We could keep the former for Zulip in the repository (you want a sample anyway), but obviously we don't want to check in the user's password/keys.

The other direction one could go in with making this usably be other organizations is having the configuration somehow live in the GitHub "integration" page (if that's possible), so that other orgs using it don't need to run their own copy of zulipbot.  Probably not the right model in the short term (in that we'd want to see a few orgs using their own fork of it and contributing functionality changes first), but worth mentioning as a long-term direction.

**Comment by synicalsyntax** [comment]
Will be pushing changes to the "config" branch for a peek on what options I'm adding, feedback would be great :) 

**Currently supported options (updated 3/17)**
* Username
* Password
* Area labels & teams
* Inactive issue/PR time limit
* Abandon issue time limit
* Travis webhook notifications (for finished build statuses)
* Travis updates label name
* Self-labeling (only issue/PR authors can manage their issue/PR labels with `@zulipbot label` & `@zulipbot remove`

@zulipbot claim
